package org.kie.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MaxKeyFieldsForConstructor1 implements java.io.Serializable
{

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(0)
    @org.kie.api.definition.type.Key
    private String attribute0000;
    @org.kie.api.definition.type.Position(1)
    @org.kie.api.definition.type.Key
    private String attribute0001;
    @org.kie.api.definition.type.Position(2)
    @org.kie.api.definition.type.Key
    private String attribute0002;
    @org.kie.api.definition.type.Position(3)
    @org.kie.api.definition.type.Key
    private String attribute0003;
    @org.kie.api.definition.type.Position(4)
    @org.kie.api.definition.type.Key
    private String attribute0004;
    @org.kie.api.definition.type.Position(5)
    @org.kie.api.definition.type.Key
    private String attribute0005;
    @org.kie.api.definition.type.Position(6)
    @org.kie.api.definition.type.Key
    private String attribute0006;
    @org.kie.api.definition.type.Position(7)
    @org.kie.api.definition.type.Key
    private String attribute0007;
    @org.kie.api.definition.type.Position(8)
    @org.kie.api.definition.type.Key
    private String attribute0008;
    @org.kie.api.definition.type.Position(9)
    @org.kie.api.definition.type.Key
    private String attribute0009;
    @org.kie.api.definition.type.Position(10)
    @org.kie.api.definition.type.Key
    private String attribute0010;
    @org.kie.api.definition.type.Position(11)
    @org.kie.api.definition.type.Key
    private String attribute0011;
    @org.kie.api.definition.type.Position(12)
    @org.kie.api.definition.type.Key
    private String attribute0012;
    @org.kie.api.definition.type.Position(13)
    @org.kie.api.definition.type.Key
    private String attribute0013;
    @org.kie.api.definition.type.Position(14)
    @org.kie.api.definition.type.Key
    private String attribute0014;
    @org.kie.api.definition.type.Position(15)
    @org.kie.api.definition.type.Key
    private String attribute0015;
    @org.kie.api.definition.type.Position(16)
    @org.kie.api.definition.type.Key
    private String attribute0016;
    @org.kie.api.definition.type.Position(17)
    @org.kie.api.definition.type.Key
    private String attribute0017;
    @org.kie.api.definition.type.Position(18)
    @org.kie.api.definition.type.Key
    private String attribute0018;
    @org.kie.api.definition.type.Position(19)
    @org.kie.api.definition.type.Key
    private String attribute0019;
    @org.kie.api.definition.type.Position(20)
    @org.kie.api.definition.type.Key
    private String attribute0020;
    @org.kie.api.definition.type.Position(21)
    @org.kie.api.definition.type.Key
    private String attribute0021;
    @org.kie.api.definition.type.Position(22)
    @org.kie.api.definition.type.Key
    private String attribute0022;
    @org.kie.api.definition.type.Position(23)
    @org.kie.api.definition.type.Key
    private String attribute0023;
    @org.kie.api.definition.type.Position(24)
    @org.kie.api.definition.type.Key
    private String attribute0024;
    @org.kie.api.definition.type.Position(25)
    @org.kie.api.definition.type.Key
    private String attribute0025;
    @org.kie.api.definition.type.Position(26)
    @org.kie.api.definition.type.Key
    private String attribute0026;
    @org.kie.api.definition.type.Position(27)
    @org.kie.api.definition.type.Key
    private String attribute0027;
    @org.kie.api.definition.type.Position(28)
    @org.kie.api.definition.type.Key
    private String attribute0028;
    @org.kie.api.definition.type.Position(29)
    @org.kie.api.definition.type.Key
    private String attribute0029;
    @org.kie.api.definition.type.Position(30)
    @org.kie.api.definition.type.Key
    private String attribute0030;
    @org.kie.api.definition.type.Position(31)
    @org.kie.api.definition.type.Key
    private String attribute0031;
    @org.kie.api.definition.type.Position(32)
    @org.kie.api.definition.type.Key
    private String attribute0032;
    @org.kie.api.definition.type.Position(33)
    @org.kie.api.definition.type.Key
    private String attribute0033;
    @org.kie.api.definition.type.Position(34)
    @org.kie.api.definition.type.Key
    private String attribute0034;
    @org.kie.api.definition.type.Position(35)
    @org.kie.api.definition.type.Key
    private String attribute0035;
    @org.kie.api.definition.type.Position(36)
    @org.kie.api.definition.type.Key
    private String attribute0036;
    @org.kie.api.definition.type.Position(37)
    @org.kie.api.definition.type.Key
    private String attribute0037;
    @org.kie.api.definition.type.Position(38)
    @org.kie.api.definition.type.Key
    private String attribute0038;
    @org.kie.api.definition.type.Position(39)
    @org.kie.api.definition.type.Key
    private String attribute0039;
    @org.kie.api.definition.type.Position(40)
    @org.kie.api.definition.type.Key
    private String attribute0040;
    @org.kie.api.definition.type.Position(41)
    @org.kie.api.definition.type.Key
    private String attribute0041;
    @org.kie.api.definition.type.Position(42)
    @org.kie.api.definition.type.Key
    private String attribute0042;
    @org.kie.api.definition.type.Position(43)
    @org.kie.api.definition.type.Key
    private String attribute0043;
    @org.kie.api.definition.type.Position(44)
    @org.kie.api.definition.type.Key
    private String attribute0044;
    @org.kie.api.definition.type.Position(45)
    @org.kie.api.definition.type.Key
    private String attribute0045;
    @org.kie.api.definition.type.Position(46)
    @org.kie.api.definition.type.Key
    private String attribute0046;
    @org.kie.api.definition.type.Position(47)
    @org.kie.api.definition.type.Key
    private String attribute0047;
    @org.kie.api.definition.type.Position(48)
    @org.kie.api.definition.type.Key
    private String attribute0048;
    @org.kie.api.definition.type.Position(49)
    @org.kie.api.definition.type.Key
    private String attribute0049;
    @org.kie.api.definition.type.Position(50)
    @org.kie.api.definition.type.Key
    private String attribute0050;
    @org.kie.api.definition.type.Position(51)
    @org.kie.api.definition.type.Key
    private String attribute0051;
    @org.kie.api.definition.type.Position(52)
    @org.kie.api.definition.type.Key
    private String attribute0052;
    @org.kie.api.definition.type.Position(53)
    @org.kie.api.definition.type.Key
    private String attribute0053;
    @org.kie.api.definition.type.Position(54)
    @org.kie.api.definition.type.Key
    private String attribute0054;
    @org.kie.api.definition.type.Position(55)
    @org.kie.api.definition.type.Key
    private String attribute0055;
    @org.kie.api.definition.type.Position(56)
    @org.kie.api.definition.type.Key
    private String attribute0056;
    @org.kie.api.definition.type.Position(57)
    @org.kie.api.definition.type.Key
    private String attribute0057;
    @org.kie.api.definition.type.Position(58)
    @org.kie.api.definition.type.Key
    private String attribute0058;
    @org.kie.api.definition.type.Position(59)
    @org.kie.api.definition.type.Key
    private String attribute0059;
    @org.kie.api.definition.type.Position(60)
    @org.kie.api.definition.type.Key
    private String attribute0060;
    @org.kie.api.definition.type.Position(61)
    @org.kie.api.definition.type.Key
    private String attribute0061;
    @org.kie.api.definition.type.Position(62)
    @org.kie.api.definition.type.Key
    private String attribute0062;
    @org.kie.api.definition.type.Position(63)
    @org.kie.api.definition.type.Key
    private String attribute0063;
    @org.kie.api.definition.type.Position(64)
    @org.kie.api.definition.type.Key
    private String attribute0064;
    @org.kie.api.definition.type.Position(65)
    @org.kie.api.definition.type.Key
    private String attribute0065;
    @org.kie.api.definition.type.Position(66)
    @org.kie.api.definition.type.Key
    private String attribute0066;
    @org.kie.api.definition.type.Position(67)
    @org.kie.api.definition.type.Key
    private String attribute0067;
    @org.kie.api.definition.type.Position(68)
    @org.kie.api.definition.type.Key
    private String attribute0068;
    @org.kie.api.definition.type.Position(69)
    @org.kie.api.definition.type.Key
    private String attribute0069;
    @org.kie.api.definition.type.Position(70)
    @org.kie.api.definition.type.Key
    private String attribute0070;
    @org.kie.api.definition.type.Position(71)
    @org.kie.api.definition.type.Key
    private String attribute0071;
    @org.kie.api.definition.type.Position(72)
    @org.kie.api.definition.type.Key
    private String attribute0072;
    @org.kie.api.definition.type.Position(73)
    @org.kie.api.definition.type.Key
    private String attribute0073;
    @org.kie.api.definition.type.Position(74)
    @org.kie.api.definition.type.Key
    private String attribute0074;
    @org.kie.api.definition.type.Position(75)
    @org.kie.api.definition.type.Key
    private String attribute0075;
    @org.kie.api.definition.type.Position(76)
    @org.kie.api.definition.type.Key
    private String attribute0076;
    @org.kie.api.definition.type.Position(77)
    @org.kie.api.definition.type.Key
    private String attribute0077;
    @org.kie.api.definition.type.Position(78)
    @org.kie.api.definition.type.Key
    private String attribute0078;
    @org.kie.api.definition.type.Position(79)
    @org.kie.api.definition.type.Key
    private String attribute0079;
    @org.kie.api.definition.type.Position(80)
    @org.kie.api.definition.type.Key
    private String attribute0080;
    @org.kie.api.definition.type.Position(81)
    @org.kie.api.definition.type.Key
    private String attribute0081;
    @org.kie.api.definition.type.Position(82)
    @org.kie.api.definition.type.Key
    private String attribute0082;
    @org.kie.api.definition.type.Position(83)
    @org.kie.api.definition.type.Key
    private String attribute0083;
    @org.kie.api.definition.type.Position(84)
    @org.kie.api.definition.type.Key
    private String attribute0084;
    @org.kie.api.definition.type.Position(85)
    @org.kie.api.definition.type.Key
    private String attribute0085;
    @org.kie.api.definition.type.Position(86)
    @org.kie.api.definition.type.Key
    private String attribute0086;
    @org.kie.api.definition.type.Position(87)
    @org.kie.api.definition.type.Key
    private String attribute0087;
    @org.kie.api.definition.type.Position(88)
    @org.kie.api.definition.type.Key
    private String attribute0088;
    @org.kie.api.definition.type.Position(89)
    @org.kie.api.definition.type.Key
    private String attribute0089;
    @org.kie.api.definition.type.Position(90)
    @org.kie.api.definition.type.Key
    private String attribute0090;
    @org.kie.api.definition.type.Position(91)
    @org.kie.api.definition.type.Key
    private String attribute0091;
    @org.kie.api.definition.type.Position(92)
    @org.kie.api.definition.type.Key
    private String attribute0092;
    @org.kie.api.definition.type.Position(93)
    @org.kie.api.definition.type.Key
    private String attribute0093;
    @org.kie.api.definition.type.Position(94)
    @org.kie.api.definition.type.Key
    private String attribute0094;
    @org.kie.api.definition.type.Position(95)
    @org.kie.api.definition.type.Key
    private String attribute0095;
    @org.kie.api.definition.type.Position(96)
    @org.kie.api.definition.type.Key
    private String attribute0096;
    @org.kie.api.definition.type.Position(97)
    @org.kie.api.definition.type.Key
    private String attribute0097;
    @org.kie.api.definition.type.Position(98)
    @org.kie.api.definition.type.Key
    private String attribute0098;
    @org.kie.api.definition.type.Position(99)
    @org.kie.api.definition.type.Key
    private String attribute0099;
    @org.kie.api.definition.type.Position(100)
    @org.kie.api.definition.type.Key
    private String attribute0100;
    @org.kie.api.definition.type.Position(101)
    @org.kie.api.definition.type.Key
    private String attribute0101;
    @org.kie.api.definition.type.Position(102)
    @org.kie.api.definition.type.Key
    private String attribute0102;
    @org.kie.api.definition.type.Position(103)
    @org.kie.api.definition.type.Key
    private String attribute0103;
    @org.kie.api.definition.type.Position(104)
    @org.kie.api.definition.type.Key
    private String attribute0104;
    @org.kie.api.definition.type.Position(105)
    @org.kie.api.definition.type.Key
    private String attribute0105;
    @org.kie.api.definition.type.Position(106)
    @org.kie.api.definition.type.Key
    private String attribute0106;
    @org.kie.api.definition.type.Position(107)
    @org.kie.api.definition.type.Key
    private String attribute0107;
    @org.kie.api.definition.type.Position(108)
    @org.kie.api.definition.type.Key
    private String attribute0108;
    @org.kie.api.definition.type.Position(109)
    @org.kie.api.definition.type.Key
    private String attribute0109;
    @org.kie.api.definition.type.Position(110)
    @org.kie.api.definition.type.Key
    private String attribute0110;
    @org.kie.api.definition.type.Position(111)
    @org.kie.api.definition.type.Key
    private String attribute0111;
    @org.kie.api.definition.type.Position(112)
    @org.kie.api.definition.type.Key
    private String attribute0112;
    @org.kie.api.definition.type.Position(113)
    @org.kie.api.definition.type.Key
    private String attribute0113;
    @org.kie.api.definition.type.Position(114)
    @org.kie.api.definition.type.Key
    private String attribute0114;
    @org.kie.api.definition.type.Position(115)
    @org.kie.api.definition.type.Key
    private String attribute0115;
    @org.kie.api.definition.type.Position(116)
    @org.kie.api.definition.type.Key
    private String attribute0116;
    @org.kie.api.definition.type.Position(117)
    @org.kie.api.definition.type.Key
    private String attribute0117;
    @org.kie.api.definition.type.Position(118)
    @org.kie.api.definition.type.Key
    private String attribute0118;

    public MaxKeyFieldsForConstructor1()
    {
    }

    public MaxKeyFieldsForConstructor1( java.lang.String attribute0000,
            java.lang.String attribute0001, java.lang.String attribute0002,
            java.lang.String attribute0003, java.lang.String attribute0004,
            java.lang.String attribute0005, java.lang.String attribute0006,
            java.lang.String attribute0007, java.lang.String attribute0008,
            java.lang.String attribute0009, java.lang.String attribute0010,
            java.lang.String attribute0011, java.lang.String attribute0012,
            java.lang.String attribute0013, java.lang.String attribute0014,
            java.lang.String attribute0015, java.lang.String attribute0016,
            java.lang.String attribute0017, java.lang.String attribute0018,
            java.lang.String attribute0019, java.lang.String attribute0020,
            java.lang.String attribute0021, java.lang.String attribute0022,
            java.lang.String attribute0023, java.lang.String attribute0024,
            java.lang.String attribute0025, java.lang.String attribute0026,
            java.lang.String attribute0027, java.lang.String attribute0028,
            java.lang.String attribute0029, java.lang.String attribute0030,
            java.lang.String attribute0031, java.lang.String attribute0032,
            java.lang.String attribute0033, java.lang.String attribute0034,
            java.lang.String attribute0035, java.lang.String attribute0036,
            java.lang.String attribute0037, java.lang.String attribute0038,
            java.lang.String attribute0039, java.lang.String attribute0040,
            java.lang.String attribute0041, java.lang.String attribute0042,
            java.lang.String attribute0043, java.lang.String attribute0044,
            java.lang.String attribute0045, java.lang.String attribute0046,
            java.lang.String attribute0047, java.lang.String attribute0048,
            java.lang.String attribute0049, java.lang.String attribute0050,
            java.lang.String attribute0051, java.lang.String attribute0052,
            java.lang.String attribute0053, java.lang.String attribute0054,
            java.lang.String attribute0055, java.lang.String attribute0056,
            java.lang.String attribute0057, java.lang.String attribute0058,
            java.lang.String attribute0059, java.lang.String attribute0060,
            java.lang.String attribute0061, java.lang.String attribute0062,
            java.lang.String attribute0063, java.lang.String attribute0064,
            java.lang.String attribute0065, java.lang.String attribute0066,
            java.lang.String attribute0067, java.lang.String attribute0068,
            java.lang.String attribute0069, java.lang.String attribute0070,
            java.lang.String attribute0071, java.lang.String attribute0072,
            java.lang.String attribute0073, java.lang.String attribute0074,
            java.lang.String attribute0075, java.lang.String attribute0076,
            java.lang.String attribute0077, java.lang.String attribute0078,
            java.lang.String attribute0079, java.lang.String attribute0080,
            java.lang.String attribute0081, java.lang.String attribute0082,
            java.lang.String attribute0083, java.lang.String attribute0084,
            java.lang.String attribute0085, java.lang.String attribute0086,
            java.lang.String attribute0087, java.lang.String attribute0088,
            java.lang.String attribute0089, java.lang.String attribute0090,
            java.lang.String attribute0091, java.lang.String attribute0092,
            java.lang.String attribute0093, java.lang.String attribute0094,
            java.lang.String attribute0095, java.lang.String attribute0096,
            java.lang.String attribute0097, java.lang.String attribute0098,
            java.lang.String attribute0099, java.lang.String attribute0100,
            java.lang.String attribute0101, java.lang.String attribute0102,
            java.lang.String attribute0103, java.lang.String attribute0104,
            java.lang.String attribute0105, java.lang.String attribute0106,
            java.lang.String attribute0107, java.lang.String attribute0108,
            java.lang.String attribute0109, java.lang.String attribute0110,
            java.lang.String attribute0111, java.lang.String attribute0112,
            java.lang.String attribute0113, java.lang.String attribute0114,
            java.lang.String attribute0115, java.lang.String attribute0116,
            java.lang.String attribute0117, java.lang.String attribute0118 )
    {
        this.attribute0000 = attribute0000;
        this.attribute0001 = attribute0001;
        this.attribute0002 = attribute0002;
        this.attribute0003 = attribute0003;
        this.attribute0004 = attribute0004;
        this.attribute0005 = attribute0005;
        this.attribute0006 = attribute0006;
        this.attribute0007 = attribute0007;
        this.attribute0008 = attribute0008;
        this.attribute0009 = attribute0009;
        this.attribute0010 = attribute0010;
        this.attribute0011 = attribute0011;
        this.attribute0012 = attribute0012;
        this.attribute0013 = attribute0013;
        this.attribute0014 = attribute0014;
        this.attribute0015 = attribute0015;
        this.attribute0016 = attribute0016;
        this.attribute0017 = attribute0017;
        this.attribute0018 = attribute0018;
        this.attribute0019 = attribute0019;
        this.attribute0020 = attribute0020;
        this.attribute0021 = attribute0021;
        this.attribute0022 = attribute0022;
        this.attribute0023 = attribute0023;
        this.attribute0024 = attribute0024;
        this.attribute0025 = attribute0025;
        this.attribute0026 = attribute0026;
        this.attribute0027 = attribute0027;
        this.attribute0028 = attribute0028;
        this.attribute0029 = attribute0029;
        this.attribute0030 = attribute0030;
        this.attribute0031 = attribute0031;
        this.attribute0032 = attribute0032;
        this.attribute0033 = attribute0033;
        this.attribute0034 = attribute0034;
        this.attribute0035 = attribute0035;
        this.attribute0036 = attribute0036;
        this.attribute0037 = attribute0037;
        this.attribute0038 = attribute0038;
        this.attribute0039 = attribute0039;
        this.attribute0040 = attribute0040;
        this.attribute0041 = attribute0041;
        this.attribute0042 = attribute0042;
        this.attribute0043 = attribute0043;
        this.attribute0044 = attribute0044;
        this.attribute0045 = attribute0045;
        this.attribute0046 = attribute0046;
        this.attribute0047 = attribute0047;
        this.attribute0048 = attribute0048;
        this.attribute0049 = attribute0049;
        this.attribute0050 = attribute0050;
        this.attribute0051 = attribute0051;
        this.attribute0052 = attribute0052;
        this.attribute0053 = attribute0053;
        this.attribute0054 = attribute0054;
        this.attribute0055 = attribute0055;
        this.attribute0056 = attribute0056;
        this.attribute0057 = attribute0057;
        this.attribute0058 = attribute0058;
        this.attribute0059 = attribute0059;
        this.attribute0060 = attribute0060;
        this.attribute0061 = attribute0061;
        this.attribute0062 = attribute0062;
        this.attribute0063 = attribute0063;
        this.attribute0064 = attribute0064;
        this.attribute0065 = attribute0065;
        this.attribute0066 = attribute0066;
        this.attribute0067 = attribute0067;
        this.attribute0068 = attribute0068;
        this.attribute0069 = attribute0069;
        this.attribute0070 = attribute0070;
        this.attribute0071 = attribute0071;
        this.attribute0072 = attribute0072;
        this.attribute0073 = attribute0073;
        this.attribute0074 = attribute0074;
        this.attribute0075 = attribute0075;
        this.attribute0076 = attribute0076;
        this.attribute0077 = attribute0077;
        this.attribute0078 = attribute0078;
        this.attribute0079 = attribute0079;
        this.attribute0080 = attribute0080;
        this.attribute0081 = attribute0081;
        this.attribute0082 = attribute0082;
        this.attribute0083 = attribute0083;
        this.attribute0084 = attribute0084;
        this.attribute0085 = attribute0085;
        this.attribute0086 = attribute0086;
        this.attribute0087 = attribute0087;
        this.attribute0088 = attribute0088;
        this.attribute0089 = attribute0089;
        this.attribute0090 = attribute0090;
        this.attribute0091 = attribute0091;
        this.attribute0092 = attribute0092;
        this.attribute0093 = attribute0093;
        this.attribute0094 = attribute0094;
        this.attribute0095 = attribute0095;
        this.attribute0096 = attribute0096;
        this.attribute0097 = attribute0097;
        this.attribute0098 = attribute0098;
        this.attribute0099 = attribute0099;
        this.attribute0100 = attribute0100;
        this.attribute0101 = attribute0101;
        this.attribute0102 = attribute0102;
        this.attribute0103 = attribute0103;
        this.attribute0104 = attribute0104;
        this.attribute0105 = attribute0105;
        this.attribute0106 = attribute0106;
        this.attribute0107 = attribute0107;
        this.attribute0108 = attribute0108;
        this.attribute0109 = attribute0109;
        this.attribute0110 = attribute0110;
        this.attribute0111 = attribute0111;
        this.attribute0112 = attribute0112;
        this.attribute0113 = attribute0113;
        this.attribute0114 = attribute0114;
        this.attribute0115 = attribute0115;
        this.attribute0116 = attribute0116;
        this.attribute0117 = attribute0117;
        this.attribute0118 = attribute0118;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        org.kie.test.MaxKeyFieldsForConstructor1 that = (org.kie.test.MaxKeyFieldsForConstructor1) o;
        if (attribute0000 != null ? !attribute0000.equals(that.attribute0000)
                : that.attribute0000 != null)
            return false;
        if (attribute0001 != null ? !attribute0001.equals(that.attribute0001)
                : that.attribute0001 != null)
            return false;
        if (attribute0002 != null ? !attribute0002.equals(that.attribute0002)
                : that.attribute0002 != null)
            return false;
        if (attribute0003 != null ? !attribute0003.equals(that.attribute0003)
                : that.attribute0003 != null)
            return false;
        if (attribute0004 != null ? !attribute0004.equals(that.attribute0004)
                : that.attribute0004 != null)
            return false;
        if (attribute0005 != null ? !attribute0005.equals(that.attribute0005)
                : that.attribute0005 != null)
            return false;
        if (attribute0006 != null ? !attribute0006.equals(that.attribute0006)
                : that.attribute0006 != null)
            return false;
        if (attribute0007 != null ? !attribute0007.equals(that.attribute0007)
                : that.attribute0007 != null)
            return false;
        if (attribute0008 != null ? !attribute0008.equals(that.attribute0008)
                : that.attribute0008 != null)
            return false;
        if (attribute0009 != null ? !attribute0009.equals(that.attribute0009)
                : that.attribute0009 != null)
            return false;
        if (attribute0010 != null ? !attribute0010.equals(that.attribute0010)
                : that.attribute0010 != null)
            return false;
        if (attribute0011 != null ? !attribute0011.equals(that.attribute0011)
                : that.attribute0011 != null)
            return false;
        if (attribute0012 != null ? !attribute0012.equals(that.attribute0012)
                : that.attribute0012 != null)
            return false;
        if (attribute0013 != null ? !attribute0013.equals(that.attribute0013)
                : that.attribute0013 != null)
            return false;
        if (attribute0014 != null ? !attribute0014.equals(that.attribute0014)
                : that.attribute0014 != null)
            return false;
        if (attribute0015 != null ? !attribute0015.equals(that.attribute0015)
                : that.attribute0015 != null)
            return false;
        if (attribute0016 != null ? !attribute0016.equals(that.attribute0016)
                : that.attribute0016 != null)
            return false;
        if (attribute0017 != null ? !attribute0017.equals(that.attribute0017)
                : that.attribute0017 != null)
            return false;
        if (attribute0018 != null ? !attribute0018.equals(that.attribute0018)
                : that.attribute0018 != null)
            return false;
        if (attribute0019 != null ? !attribute0019.equals(that.attribute0019)
                : that.attribute0019 != null)
            return false;
        if (attribute0020 != null ? !attribute0020.equals(that.attribute0020)
                : that.attribute0020 != null)
            return false;
        if (attribute0021 != null ? !attribute0021.equals(that.attribute0021)
                : that.attribute0021 != null)
            return false;
        if (attribute0022 != null ? !attribute0022.equals(that.attribute0022)
                : that.attribute0022 != null)
            return false;
        if (attribute0023 != null ? !attribute0023.equals(that.attribute0023)
                : that.attribute0023 != null)
            return false;
        if (attribute0024 != null ? !attribute0024.equals(that.attribute0024)
                : that.attribute0024 != null)
            return false;
        if (attribute0025 != null ? !attribute0025.equals(that.attribute0025)
                : that.attribute0025 != null)
            return false;
        if (attribute0026 != null ? !attribute0026.equals(that.attribute0026)
                : that.attribute0026 != null)
            return false;
        if (attribute0027 != null ? !attribute0027.equals(that.attribute0027)
                : that.attribute0027 != null)
            return false;
        if (attribute0028 != null ? !attribute0028.equals(that.attribute0028)
                : that.attribute0028 != null)
            return false;
        if (attribute0029 != null ? !attribute0029.equals(that.attribute0029)
                : that.attribute0029 != null)
            return false;
        if (attribute0030 != null ? !attribute0030.equals(that.attribute0030)
                : that.attribute0030 != null)
            return false;
        if (attribute0031 != null ? !attribute0031.equals(that.attribute0031)
                : that.attribute0031 != null)
            return false;
        if (attribute0032 != null ? !attribute0032.equals(that.attribute0032)
                : that.attribute0032 != null)
            return false;
        if (attribute0033 != null ? !attribute0033.equals(that.attribute0033)
                : that.attribute0033 != null)
            return false;
        if (attribute0034 != null ? !attribute0034.equals(that.attribute0034)
                : that.attribute0034 != null)
            return false;
        if (attribute0035 != null ? !attribute0035.equals(that.attribute0035)
                : that.attribute0035 != null)
            return false;
        if (attribute0036 != null ? !attribute0036.equals(that.attribute0036)
                : that.attribute0036 != null)
            return false;
        if (attribute0037 != null ? !attribute0037.equals(that.attribute0037)
                : that.attribute0037 != null)
            return false;
        if (attribute0038 != null ? !attribute0038.equals(that.attribute0038)
                : that.attribute0038 != null)
            return false;
        if (attribute0039 != null ? !attribute0039.equals(that.attribute0039)
                : that.attribute0039 != null)
            return false;
        if (attribute0040 != null ? !attribute0040.equals(that.attribute0040)
                : that.attribute0040 != null)
            return false;
        if (attribute0041 != null ? !attribute0041.equals(that.attribute0041)
                : that.attribute0041 != null)
            return false;
        if (attribute0042 != null ? !attribute0042.equals(that.attribute0042)
                : that.attribute0042 != null)
            return false;
        if (attribute0043 != null ? !attribute0043.equals(that.attribute0043)
                : that.attribute0043 != null)
            return false;
        if (attribute0044 != null ? !attribute0044.equals(that.attribute0044)
                : that.attribute0044 != null)
            return false;
        if (attribute0045 != null ? !attribute0045.equals(that.attribute0045)
                : that.attribute0045 != null)
            return false;
        if (attribute0046 != null ? !attribute0046.equals(that.attribute0046)
                : that.attribute0046 != null)
            return false;
        if (attribute0047 != null ? !attribute0047.equals(that.attribute0047)
                : that.attribute0047 != null)
            return false;
        if (attribute0048 != null ? !attribute0048.equals(that.attribute0048)
                : that.attribute0048 != null)
            return false;
        if (attribute0049 != null ? !attribute0049.equals(that.attribute0049)
                : that.attribute0049 != null)
            return false;
        if (attribute0050 != null ? !attribute0050.equals(that.attribute0050)
                : that.attribute0050 != null)
            return false;
        if (attribute0051 != null ? !attribute0051.equals(that.attribute0051)
                : that.attribute0051 != null)
            return false;
        if (attribute0052 != null ? !attribute0052.equals(that.attribute0052)
                : that.attribute0052 != null)
            return false;
        if (attribute0053 != null ? !attribute0053.equals(that.attribute0053)
                : that.attribute0053 != null)
            return false;
        if (attribute0054 != null ? !attribute0054.equals(that.attribute0054)
                : that.attribute0054 != null)
            return false;
        if (attribute0055 != null ? !attribute0055.equals(that.attribute0055)
                : that.attribute0055 != null)
            return false;
        if (attribute0056 != null ? !attribute0056.equals(that.attribute0056)
                : that.attribute0056 != null)
            return false;
        if (attribute0057 != null ? !attribute0057.equals(that.attribute0057)
                : that.attribute0057 != null)
            return false;
        if (attribute0058 != null ? !attribute0058.equals(that.attribute0058)
                : that.attribute0058 != null)
            return false;
        if (attribute0059 != null ? !attribute0059.equals(that.attribute0059)
                : that.attribute0059 != null)
            return false;
        if (attribute0060 != null ? !attribute0060.equals(that.attribute0060)
                : that.attribute0060 != null)
            return false;
        if (attribute0061 != null ? !attribute0061.equals(that.attribute0061)
                : that.attribute0061 != null)
            return false;
        if (attribute0062 != null ? !attribute0062.equals(that.attribute0062)
                : that.attribute0062 != null)
            return false;
        if (attribute0063 != null ? !attribute0063.equals(that.attribute0063)
                : that.attribute0063 != null)
            return false;
        if (attribute0064 != null ? !attribute0064.equals(that.attribute0064)
                : that.attribute0064 != null)
            return false;
        if (attribute0065 != null ? !attribute0065.equals(that.attribute0065)
                : that.attribute0065 != null)
            return false;
        if (attribute0066 != null ? !attribute0066.equals(that.attribute0066)
                : that.attribute0066 != null)
            return false;
        if (attribute0067 != null ? !attribute0067.equals(that.attribute0067)
                : that.attribute0067 != null)
            return false;
        if (attribute0068 != null ? !attribute0068.equals(that.attribute0068)
                : that.attribute0068 != null)
            return false;
        if (attribute0069 != null ? !attribute0069.equals(that.attribute0069)
                : that.attribute0069 != null)
            return false;
        if (attribute0070 != null ? !attribute0070.equals(that.attribute0070)
                : that.attribute0070 != null)
            return false;
        if (attribute0071 != null ? !attribute0071.equals(that.attribute0071)
                : that.attribute0071 != null)
            return false;
        if (attribute0072 != null ? !attribute0072.equals(that.attribute0072)
                : that.attribute0072 != null)
            return false;
        if (attribute0073 != null ? !attribute0073.equals(that.attribute0073)
                : that.attribute0073 != null)
            return false;
        if (attribute0074 != null ? !attribute0074.equals(that.attribute0074)
                : that.attribute0074 != null)
            return false;
        if (attribute0075 != null ? !attribute0075.equals(that.attribute0075)
                : that.attribute0075 != null)
            return false;
        if (attribute0076 != null ? !attribute0076.equals(that.attribute0076)
                : that.attribute0076 != null)
            return false;
        if (attribute0077 != null ? !attribute0077.equals(that.attribute0077)
                : that.attribute0077 != null)
            return false;
        if (attribute0078 != null ? !attribute0078.equals(that.attribute0078)
                : that.attribute0078 != null)
            return false;
        if (attribute0079 != null ? !attribute0079.equals(that.attribute0079)
                : that.attribute0079 != null)
            return false;
        if (attribute0080 != null ? !attribute0080.equals(that.attribute0080)
                : that.attribute0080 != null)
            return false;
        if (attribute0081 != null ? !attribute0081.equals(that.attribute0081)
                : that.attribute0081 != null)
            return false;
        if (attribute0082 != null ? !attribute0082.equals(that.attribute0082)
                : that.attribute0082 != null)
            return false;
        if (attribute0083 != null ? !attribute0083.equals(that.attribute0083)
                : that.attribute0083 != null)
            return false;
        if (attribute0084 != null ? !attribute0084.equals(that.attribute0084)
                : that.attribute0084 != null)
            return false;
        if (attribute0085 != null ? !attribute0085.equals(that.attribute0085)
                : that.attribute0085 != null)
            return false;
        if (attribute0086 != null ? !attribute0086.equals(that.attribute0086)
                : that.attribute0086 != null)
            return false;
        if (attribute0087 != null ? !attribute0087.equals(that.attribute0087)
                : that.attribute0087 != null)
            return false;
        if (attribute0088 != null ? !attribute0088.equals(that.attribute0088)
                : that.attribute0088 != null)
            return false;
        if (attribute0089 != null ? !attribute0089.equals(that.attribute0089)
                : that.attribute0089 != null)
            return false;
        if (attribute0090 != null ? !attribute0090.equals(that.attribute0090)
                : that.attribute0090 != null)
            return false;
        if (attribute0091 != null ? !attribute0091.equals(that.attribute0091)
                : that.attribute0091 != null)
            return false;
        if (attribute0092 != null ? !attribute0092.equals(that.attribute0092)
                : that.attribute0092 != null)
            return false;
        if (attribute0093 != null ? !attribute0093.equals(that.attribute0093)
                : that.attribute0093 != null)
            return false;
        if (attribute0094 != null ? !attribute0094.equals(that.attribute0094)
                : that.attribute0094 != null)
            return false;
        if (attribute0095 != null ? !attribute0095.equals(that.attribute0095)
                : that.attribute0095 != null)
            return false;
        if (attribute0096 != null ? !attribute0096.equals(that.attribute0096)
                : that.attribute0096 != null)
            return false;
        if (attribute0097 != null ? !attribute0097.equals(that.attribute0097)
                : that.attribute0097 != null)
            return false;
        if (attribute0098 != null ? !attribute0098.equals(that.attribute0098)
                : that.attribute0098 != null)
            return false;
        if (attribute0099 != null ? !attribute0099.equals(that.attribute0099)
                : that.attribute0099 != null)
            return false;
        if (attribute0100 != null ? !attribute0100.equals(that.attribute0100)
                : that.attribute0100 != null)
            return false;
        if (attribute0101 != null ? !attribute0101.equals(that.attribute0101)
                : that.attribute0101 != null)
            return false;
        if (attribute0102 != null ? !attribute0102.equals(that.attribute0102)
                : that.attribute0102 != null)
            return false;
        if (attribute0103 != null ? !attribute0103.equals(that.attribute0103)
                : that.attribute0103 != null)
            return false;
        if (attribute0104 != null ? !attribute0104.equals(that.attribute0104)
                : that.attribute0104 != null)
            return false;
        if (attribute0105 != null ? !attribute0105.equals(that.attribute0105)
                : that.attribute0105 != null)
            return false;
        if (attribute0106 != null ? !attribute0106.equals(that.attribute0106)
                : that.attribute0106 != null)
            return false;
        if (attribute0107 != null ? !attribute0107.equals(that.attribute0107)
                : that.attribute0107 != null)
            return false;
        if (attribute0108 != null ? !attribute0108.equals(that.attribute0108)
                : that.attribute0108 != null)
            return false;
        if (attribute0109 != null ? !attribute0109.equals(that.attribute0109)
                : that.attribute0109 != null)
            return false;
        if (attribute0110 != null ? !attribute0110.equals(that.attribute0110)
                : that.attribute0110 != null)
            return false;
        if (attribute0111 != null ? !attribute0111.equals(that.attribute0111)
                : that.attribute0111 != null)
            return false;
        if (attribute0112 != null ? !attribute0112.equals(that.attribute0112)
                : that.attribute0112 != null)
            return false;
        if (attribute0113 != null ? !attribute0113.equals(that.attribute0113)
                : that.attribute0113 != null)
            return false;
        if (attribute0114 != null ? !attribute0114.equals(that.attribute0114)
                : that.attribute0114 != null)
            return false;
        if (attribute0115 != null ? !attribute0115.equals(that.attribute0115)
                : that.attribute0115 != null)
            return false;
        if (attribute0116 != null ? !attribute0116.equals(that.attribute0116)
                : that.attribute0116 != null)
            return false;
        if (attribute0117 != null ? !attribute0117.equals(that.attribute0117)
                : that.attribute0117 != null)
            return false;
        if (attribute0118 != null ? !attribute0118.equals(that.attribute0118)
                : that.attribute0118 != null)
            return false;
        return true;
    }

    @Override
    public int hashCode()
    {
        int result = 17;
        result = 31 * result
                + (attribute0000 != null ? attribute0000.hashCode() : 0);
        result = 31 * result
                + (attribute0001 != null ? attribute0001.hashCode() : 0);
        result = 31 * result
                + (attribute0002 != null ? attribute0002.hashCode() : 0);
        result = 31 * result
                + (attribute0003 != null ? attribute0003.hashCode() : 0);
        result = 31 * result
                + (attribute0004 != null ? attribute0004.hashCode() : 0);
        result = 31 * result
                + (attribute0005 != null ? attribute0005.hashCode() : 0);
        result = 31 * result
                + (attribute0006 != null ? attribute0006.hashCode() : 0);
        result = 31 * result
                + (attribute0007 != null ? attribute0007.hashCode() : 0);
        result = 31 * result
                + (attribute0008 != null ? attribute0008.hashCode() : 0);
        result = 31 * result
                + (attribute0009 != null ? attribute0009.hashCode() : 0);
        result = 31 * result
                + (attribute0010 != null ? attribute0010.hashCode() : 0);
        result = 31 * result
                + (attribute0011 != null ? attribute0011.hashCode() : 0);
        result = 31 * result
                + (attribute0012 != null ? attribute0012.hashCode() : 0);
        result = 31 * result
                + (attribute0013 != null ? attribute0013.hashCode() : 0);
        result = 31 * result
                + (attribute0014 != null ? attribute0014.hashCode() : 0);
        result = 31 * result
                + (attribute0015 != null ? attribute0015.hashCode() : 0);
        result = 31 * result
                + (attribute0016 != null ? attribute0016.hashCode() : 0);
        result = 31 * result
                + (attribute0017 != null ? attribute0017.hashCode() : 0);
        result = 31 * result
                + (attribute0018 != null ? attribute0018.hashCode() : 0);
        result = 31 * result
                + (attribute0019 != null ? attribute0019.hashCode() : 0);
        result = 31 * result
                + (attribute0020 != null ? attribute0020.hashCode() : 0);
        result = 31 * result
                + (attribute0021 != null ? attribute0021.hashCode() : 0);
        result = 31 * result
                + (attribute0022 != null ? attribute0022.hashCode() : 0);
        result = 31 * result
                + (attribute0023 != null ? attribute0023.hashCode() : 0);
        result = 31 * result
                + (attribute0024 != null ? attribute0024.hashCode() : 0);
        result = 31 * result
                + (attribute0025 != null ? attribute0025.hashCode() : 0);
        result = 31 * result
                + (attribute0026 != null ? attribute0026.hashCode() : 0);
        result = 31 * result
                + (attribute0027 != null ? attribute0027.hashCode() : 0);
        result = 31 * result
                + (attribute0028 != null ? attribute0028.hashCode() : 0);
        result = 31 * result
                + (attribute0029 != null ? attribute0029.hashCode() : 0);
        result = 31 * result
                + (attribute0030 != null ? attribute0030.hashCode() : 0);
        result = 31 * result
                + (attribute0031 != null ? attribute0031.hashCode() : 0);
        result = 31 * result
                + (attribute0032 != null ? attribute0032.hashCode() : 0);
        result = 31 * result
                + (attribute0033 != null ? attribute0033.hashCode() : 0);
        result = 31 * result
                + (attribute0034 != null ? attribute0034.hashCode() : 0);
        result = 31 * result
                + (attribute0035 != null ? attribute0035.hashCode() : 0);
        result = 31 * result
                + (attribute0036 != null ? attribute0036.hashCode() : 0);
        result = 31 * result
                + (attribute0037 != null ? attribute0037.hashCode() : 0);
        result = 31 * result
                + (attribute0038 != null ? attribute0038.hashCode() : 0);
        result = 31 * result
                + (attribute0039 != null ? attribute0039.hashCode() : 0);
        result = 31 * result
                + (attribute0040 != null ? attribute0040.hashCode() : 0);
        result = 31 * result
                + (attribute0041 != null ? attribute0041.hashCode() : 0);
        result = 31 * result
                + (attribute0042 != null ? attribute0042.hashCode() : 0);
        result = 31 * result
                + (attribute0043 != null ? attribute0043.hashCode() : 0);
        result = 31 * result
                + (attribute0044 != null ? attribute0044.hashCode() : 0);
        result = 31 * result
                + (attribute0045 != null ? attribute0045.hashCode() : 0);
        result = 31 * result
                + (attribute0046 != null ? attribute0046.hashCode() : 0);
        result = 31 * result
                + (attribute0047 != null ? attribute0047.hashCode() : 0);
        result = 31 * result
                + (attribute0048 != null ? attribute0048.hashCode() : 0);
        result = 31 * result
                + (attribute0049 != null ? attribute0049.hashCode() : 0);
        result = 31 * result
                + (attribute0050 != null ? attribute0050.hashCode() : 0);
        result = 31 * result
                + (attribute0051 != null ? attribute0051.hashCode() : 0);
        result = 31 * result
                + (attribute0052 != null ? attribute0052.hashCode() : 0);
        result = 31 * result
                + (attribute0053 != null ? attribute0053.hashCode() : 0);
        result = 31 * result
                + (attribute0054 != null ? attribute0054.hashCode() : 0);
        result = 31 * result
                + (attribute0055 != null ? attribute0055.hashCode() : 0);
        result = 31 * result
                + (attribute0056 != null ? attribute0056.hashCode() : 0);
        result = 31 * result
                + (attribute0057 != null ? attribute0057.hashCode() : 0);
        result = 31 * result
                + (attribute0058 != null ? attribute0058.hashCode() : 0);
        result = 31 * result
                + (attribute0059 != null ? attribute0059.hashCode() : 0);
        result = 31 * result
                + (attribute0060 != null ? attribute0060.hashCode() : 0);
        result = 31 * result
                + (attribute0061 != null ? attribute0061.hashCode() : 0);
        result = 31 * result
                + (attribute0062 != null ? attribute0062.hashCode() : 0);
        result = 31 * result
                + (attribute0063 != null ? attribute0063.hashCode() : 0);
        result = 31 * result
                + (attribute0064 != null ? attribute0064.hashCode() : 0);
        result = 31 * result
                + (attribute0065 != null ? attribute0065.hashCode() : 0);
        result = 31 * result
                + (attribute0066 != null ? attribute0066.hashCode() : 0);
        result = 31 * result
                + (attribute0067 != null ? attribute0067.hashCode() : 0);
        result = 31 * result
                + (attribute0068 != null ? attribute0068.hashCode() : 0);
        result = 31 * result
                + (attribute0069 != null ? attribute0069.hashCode() : 0);
        result = 31 * result
                + (attribute0070 != null ? attribute0070.hashCode() : 0);
        result = 31 * result
                + (attribute0071 != null ? attribute0071.hashCode() : 0);
        result = 31 * result
                + (attribute0072 != null ? attribute0072.hashCode() : 0);
        result = 31 * result
                + (attribute0073 != null ? attribute0073.hashCode() : 0);
        result = 31 * result
                + (attribute0074 != null ? attribute0074.hashCode() : 0);
        result = 31 * result
                + (attribute0075 != null ? attribute0075.hashCode() : 0);
        result = 31 * result
                + (attribute0076 != null ? attribute0076.hashCode() : 0);
        result = 31 * result
                + (attribute0077 != null ? attribute0077.hashCode() : 0);
        result = 31 * result
                + (attribute0078 != null ? attribute0078.hashCode() : 0);
        result = 31 * result
                + (attribute0079 != null ? attribute0079.hashCode() : 0);
        result = 31 * result
                + (attribute0080 != null ? attribute0080.hashCode() : 0);
        result = 31 * result
                + (attribute0081 != null ? attribute0081.hashCode() : 0);
        result = 31 * result
                + (attribute0082 != null ? attribute0082.hashCode() : 0);
        result = 31 * result
                + (attribute0083 != null ? attribute0083.hashCode() : 0);
        result = 31 * result
                + (attribute0084 != null ? attribute0084.hashCode() : 0);
        result = 31 * result
                + (attribute0085 != null ? attribute0085.hashCode() : 0);
        result = 31 * result
                + (attribute0086 != null ? attribute0086.hashCode() : 0);
        result = 31 * result
                + (attribute0087 != null ? attribute0087.hashCode() : 0);
        result = 31 * result
                + (attribute0088 != null ? attribute0088.hashCode() : 0);
        result = 31 * result
                + (attribute0089 != null ? attribute0089.hashCode() : 0);
        result = 31 * result
                + (attribute0090 != null ? attribute0090.hashCode() : 0);
        result = 31 * result
                + (attribute0091 != null ? attribute0091.hashCode() : 0);
        result = 31 * result
                + (attribute0092 != null ? attribute0092.hashCode() : 0);
        result = 31 * result
                + (attribute0093 != null ? attribute0093.hashCode() : 0);
        result = 31 * result
                + (attribute0094 != null ? attribute0094.hashCode() : 0);
        result = 31 * result
                + (attribute0095 != null ? attribute0095.hashCode() : 0);
        result = 31 * result
                + (attribute0096 != null ? attribute0096.hashCode() : 0);
        result = 31 * result
                + (attribute0097 != null ? attribute0097.hashCode() : 0);
        result = 31 * result
                + (attribute0098 != null ? attribute0098.hashCode() : 0);
        result = 31 * result
                + (attribute0099 != null ? attribute0099.hashCode() : 0);
        result = 31 * result
                + (attribute0100 != null ? attribute0100.hashCode() : 0);
        result = 31 * result
                + (attribute0101 != null ? attribute0101.hashCode() : 0);
        result = 31 * result
                + (attribute0102 != null ? attribute0102.hashCode() : 0);
        result = 31 * result
                + (attribute0103 != null ? attribute0103.hashCode() : 0);
        result = 31 * result
                + (attribute0104 != null ? attribute0104.hashCode() : 0);
        result = 31 * result
                + (attribute0105 != null ? attribute0105.hashCode() : 0);
        result = 31 * result
                + (attribute0106 != null ? attribute0106.hashCode() : 0);
        result = 31 * result
                + (attribute0107 != null ? attribute0107.hashCode() : 0);
        result = 31 * result
                + (attribute0108 != null ? attribute0108.hashCode() : 0);
        result = 31 * result
                + (attribute0109 != null ? attribute0109.hashCode() : 0);
        result = 31 * result
                + (attribute0110 != null ? attribute0110.hashCode() : 0);
        result = 31 * result
                + (attribute0111 != null ? attribute0111.hashCode() : 0);
        result = 31 * result
                + (attribute0112 != null ? attribute0112.hashCode() : 0);
        result = 31 * result
                + (attribute0113 != null ? attribute0113.hashCode() : 0);
        result = 31 * result
                + (attribute0114 != null ? attribute0114.hashCode() : 0);
        result = 31 * result
                + (attribute0115 != null ? attribute0115.hashCode() : 0);
        result = 31 * result
                + (attribute0116 != null ? attribute0116.hashCode() : 0);
        result = 31 * result
                + (attribute0117 != null ? attribute0117.hashCode() : 0);
        result = 31 * result
                + (attribute0118 != null ? attribute0118.hashCode() : 0);
        return result;
    }

}