# Runs jbpm-system-test module tests periodically

name: jBPM System Test CI

on:
  schedule:
    - cron:  '0 2 * * *'

defaults:
  run:
    shell: bash

jobs:
  jbpm-system-test:
    strategy:
      matrix:
        java: [ '8', '11' ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: jbpm-system-test with java ${{ matrix.java }} and os ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      # Builds the module and runs tests 
      - name: Build jbpm-system-test with Maven
        run: |
             mvn -B clean install -f jbpm-system-test  
